### ISSUE TITLE
NO GPU FOUND

### ISSUE THREAD

**Issue by CHRIS123540** [NVIDIA/l2fwd-nv#11]
DPDK found 0 GPUs:
rte_gpu_count_avail return 0, i dont konw why.

**Comment by kongxiangcong** [comment]
I also meet with the 0 GPU problem. How do you solve this problem? Is PCIe num incorrect? thx!!!!

**Comment by ydk231912** [comment]
> 我也遇到了显卡0的问题。你如何解决这个问题？PCIe 数字错误吗？感谢！！！！

请问你们解决了吗？
